name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run isort
        uses: isort/isort-action@master
        with:
            requirementsFiles: "requirements.txt requirements_test.txt"

  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          pip install -e .
          pip install -r requirements_test.txt

      - name: Run tests
        run: pytest
